### ISSUE TITLE
Cookies werden gesetzt, bevor Einverständnis gegeben

### ISSUE THREAD

**Issue by Notme112** [LennardTFD/fff_tracker_api#5]
Hey ho!
Auf deiner Website werden Cookies gesetzt, bevor ich meine Einverständnis gegeben habe. Kannst du reproduzieren:
- Alle Cookies löschen
- neu laden
- bevor du den Dialog bestätigst auf das Schloss-Symbol in der Adressleiste klicken (Chrome)
- Cookies (2 werden verwendet)

Ich bitte, dies zu beheben @LennardTFD !
Grüße,
NiZi112

**Comment by Notme112** [comment]
Tritt leider immer noch auf...
Sorry
![image](https://user-images.githubusercontent.com/84899746/120078663-d5e0f900-c0b0-11eb-94f8-bc821b507dd3.png)
@LennardTFD

**Comment by LennardTFD** [comment]
Ich bin nur dee Entwickler mit dem Webseiten Betrieb und möglichen Updates habe ich nichts zu tun. Technische Cookies dürfen zudem ohne Zustimmung gespeichert werden.

**Comment by Notme112** [comment]
> Ich bin nur dee Entwickler mit dem Webseiten Betrieb und möglichen Updates habe ich nichts zu tun. Technische Cookies dürfen zudem ohne Zustimmung gespeichert werden.

Gut, dann habe ich nichts gesagt...
Sieht auch nach technisch notwendigem Cookie aus
